name: Run Go Code on Existing GCP Instance

on:
  push:
    branches: [ "main" ]

env:
  INSTANCE_NAME: fisrt-instance
  ZONE: us-west1-b

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Transfer code to GCP VM'
        run: |
          mkdir staging_dir
          cp -r * staging_dir
          cd staging_dir
          tar -czf mycode.tzr.gz .
          mv mycode.tar.gz ../
          cd ..
          ls
#          tar -czf mycode.tar.gz . # This will package your code into a tarball
          gcloud compute scp mycode.tar.gz mingi4754song@fisrt-instance:~/ --zone=us-west1-b

      - name: 'Run Something'
        run: |
          gcloud compute ssh mingi4754song@fisrt-instance --zone=us-west1-b --command "pwd"
          gcloud compute ssh mingi4754song@fisrt-instance --zone=us-west1-b --command "ls"
