name: Run Go Code on Existing GCP Instance

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  INSTANCE_NAME: fisrt-instance
  ZONE: us-west1-b

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: lofty-seer-397218
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Authenticate with gcloud
        run: |
          echo "$GCP_SA_KEY" > sa_key.json
          gcloud auth activate-service-account --key-file=sa_key.json
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

#      - name: Copy Go code to instance
#        run: |
#          gcloud compute scp ./main.go $INSTANCE_NAME:~/ \
#            --zone=$ZONE

#      - name: Check current user on the instance
#        run: |
#          gcloud compute ssh mingi4754song2@$INSTANCE_NAME \
#            --zone=$ZONE \
#            --command="echo 'Current user is:' && whoami"
#
#      - name: Execute Go code on instance
#        run: |
#          gcloud compute ssh mingi4754song@$INSTANCE_NAME \
#            --zone=$ZONE \
#            --command="go version"

      - name: SSH and Run Commands on Instance
        run: |
          gcloud compute ssh $INSTANCE_NAME --zone=$ZONE --command="echo 'Hello from GitHub Actions!'"

      - name: Print Current Directory
        run: pwd
