name: Run Go Code on Existing GCP Instance

on:
  push:
    branches: [ "main" ]

env:
  INSTANCE_NAME: fisrt-instance
  ZONE: us-west1-b

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20']

    steps:
      - uses: 'actions/checkout@v4'
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Display Go version
        run: go version

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Transfer code to GCP VM'
        run: |
          go build -o hello_world .
          gcloud compute scp ./hello_world mingi4754song@fisrt-instance:~/ --zone=us-west1-b

      - name: 'Run Something'
        run: |
          gcloud compute ssh mingi4754song@fisrt-instance --zone=us-west1-b --command "pwd"
          gcloud compute ssh mingi4754song@fisrt-instance --zone=us-west1-b --command "ls"
