name: CD to GCP VM

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GCP VM
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > service-account.json
          gcloud auth activate-service-account --key-file=service-account.json
          gcloud compute scp --recurse ./ first-instance:~/go/src/Keyflower --zone=us-west1-b
          gcloud compute ssh first-instance --zone=us-west1-b --command="cd ~/go/src/Keyflower && go run *.go"
